# Organization of the Course {-}

### Timetable {-}

```{r, echo=FALSE}
suppressPackageStartupMessages(library("kableExtra"))
suppressPackageStartupMessages(library("tidyverse"))

timetable <- tibble("Mondays"      = c("Theory", "Break", "Theory", "Open Coding Space"),
                    "Time"         = c("14:15-15:45", "15:45-16:15", "16:15-16:45", "16:45-17:45"),
                    "Lecture Hall" = c("Jur / Hörsaal K"))
           
timetable %>% kbl() %>%  kable_styling()
```


### Lecture Material {-}

* This online script
* [`R`-Script used during the lectures](https://www.dropbox.com/scl/fi/8foafpmricmtexnevvh2q/R_Script_CASA_2024.R?rlkey=q53jjq2x2hlcyzwbxqo7h63ez&dl=0)

### Literature {-}


* Main Course Textbook (`ISLR`): 
  * [An Introduction to Statistical Learning](https://www.statlearning.com/), by Gareth James, Daniela Witten, Trevor Hastie, and Robert Tibshirani
  * The PDF-version and further resources (datasets, etc.) of the textbook can be downloaded **for free** from [https://www.statlearning.com/](https://www.statlearning.com/)

* Further/additional reading: 
  * [The Elements of
Statistical Learning](https://hastie.su.domains/ElemStatLearn/)


<!-- * [eWhiteboard](https://www.dropbox.com/scl/fi/0znpwx8z5dllu0lecvgar/eWhiteboard_CompStat_BSc.pdf?rlkey=tcyypiqo357lhy8slj76om6td&dl=0) for lecture notes. -->

<!-- * **To-Do List for October 9, 2023:** [To-Do List (PDF)](https://www.dropbox.com/scl/fi/oxf406ur56tq4wg5hm1dj/ToDo_List_4_Students.pdf?rlkey=juskpa6o9yx903yywpgatw5j7&dl=0) -->


### Assignments {-}

For each chapter there is a home assignment. You can use the `Open Coding Space` for asking questions and for working on your assignments. You can help each other, but everyone has to submit an own home assignment.  

To participate in the assignments, you need a GitHub-Account and write your name and the name of your GitHub-Account into the following spreadsheet:</br>
[Spreadsheet](https://docs.google.com/spreadsheets/d/15NhYz8sYSogZ23FAtZkxmVMc9b4WVtvm_typ-L2xOeQ/edit?usp=sharing)


**Grading:** 

* $1$ Point per correct assignment
* $0.5$ Point if at least $50\%$ of the assignment is correct. 
* $0$ Point otherwise

**Bonus for the exam grade:**

* Upgrade of two grade steps if at least $80\%$ of the maximal possible assignment points were collected.  
* Upgrade of one grade step if less than $80\%,$ but at least $60\%$ of the maximal possible points were collected.  


<!-- ### Information on the Exam {-}

* You are allowed to use a **handwritten cheat-sheet** (**one side** of a DIN A4 page). 
* You are allowed to use a **non-programmable scientific calculator**.
* Please, do **not** use a pencil.
* Exam dates and times are published by the [examinations office](https://www.econ.uni-bonn.de/examinations/en/dates/dates?set_language=en) 
-->

<!-- * Mock Exam with 5 multiple-choice problems and 1 free-text problem: [Download](https://www.dropbox.com/scl/fi/ib7z8bp2d5q775u2hoty0/Mock_Exam1.pdf?rlkey=m5yus4dkxnekpzaoydf6eqok5&dl=0) 
   * Note: The actual exam will contain 10 multiple-choice problems and 2 free-text problems--> 

<!-- * First page of the exam (containing the exam instructions): [Download](https://www.dropbox.com/scl/fi/alnf6ny5nw801zsw73p9j/Exam_Instructions.pdf?rlkey=8etgr1y7sfwso9ad3tjkga0y9&dl=0) -->


<!-- ### Communication {-}

* You can use the Zulip-Chat [CompStat (B.Sc.)](https://ifs-bonn.zulipchat.com/join/bfmraxkf5rosbd5h3lrfa2jo/) to post questions, share codes, etc. Happy sharing and discussing!  -->
